### ISSUE TITLE
Asking for guidance by roadmap

### ISSUE THREAD

**Issue by Aryan09121** [kamranahmedse/developer-roadmap#1046]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [✓ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [✓ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ✓] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [✓ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I am a first year student and doesn't know anything about where to start and what to learn first . I have a preference for job .
So please provide me suggestions for roadmap for 1st year like what to do 

Please help me it would be a great help 
You have published many roadmap which help me a lot 
Thank you

**Comment by Steindvart** [comment]
Hi, @Aryan09121! But isn't the roadmap itself a guidance? Please, specify what exactly is your problem. What is your ultimate goal?
