### ISSUE TITLE
Sharing an Idea: Robotic/ IA roadmap 

### ISSUE THREAD

**Issue by ibandim123** [kamranahmedse/developer-roadmap#1050]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] New Roadmap

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I want ask if you can open Robotic/ IA Roadmap for students, it's important the people guide they studies with tools, language and anything else. I created one, but is more organized open  here like a branch.
![ramdon](https://user-images.githubusercontent.com/59544620/151716169-7dc40c55-44ce-47ff-892c-7efedd0cc6de.jpg)

In basic concepts we can put this: Algorithms, Language Programming(Python), Artificial Intelligence Applied, Physics Dynamics, Actuators, Sensors, Theory of Control, Cibernetic, Laws of Asimov, Definition of Robot, Machine Learning, Intelligent Agent, Specialist System and more...

**Comment by ibandim123** [comment]
![ROadMap Image](https://user-images.githubusercontent.com/59544620/151709819-63942c8f-c99b-4b5e-8c47-a0624d0332bd.png)

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
