### ISSUE TITLE
Add Kotlin language on backend roadmap

### ISSUE THREAD

**Issue by ungaratto93** [kamranahmedse/developer-roadmap#1061]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I suggest to include kotlin on side of java lang in step "learn a language".
What do you think ?

**Comment by YektaDev** [comment]
I agree.

- It's productive, modern, concise and safe.
- In terms of frameworks, not only Kotlin can be used with all existing Java frameworks, but also there are a handful of great frameworks written for it.
- There are plenty of [companies using Kotlin for sever-side development](https://kotlinlang.org/lp/server-side/case-studies/).

**Comment by Delebrith** [comment]
I'll gladly make a contribution to update the roadmap 😊

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmaps by mentioning every available option and are just focusing on what is comparatively more in-demand; comparing Kotlin to the listed options, I don't think Kotlin is as requested on job boards as the other options.

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
