### ISSUE TITLE
Add Elixir to backend Roadmap

### ISSUE THREAD

**Issue by larshei** [kamranahmedse/developer-roadmap#1117]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [X] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I saw there was an issue about adding Elixir in 2017, but a lot of time has passed, so I do not consider this a duplicate.

Elixir is based on Erlang, and Erlang
> is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. - https://www.erlang.org/

While initially built to tackle the requirements for the telecoms sector, we now have the same requirements for any (large scale) web application. Erlang comes with its own virtual machine (BEAM) and standard library (OTP) and is considered the most stable platform on the planet [[1]], running huge chunks of our internet, mobile phone and other telecommunications infrastructure.

Elixir makes the strengths of Erlang more accessible with a nicer syntax and handy additions on top.
Both [Elixir](https://elixir-lang.org/) and it's web framework [Phoenix](https://www.phoenixframework.org/) have been around and tested for quite some time and and there are tons of resources. Check out the Phoenix Framework web page to see the creation of a twitter-ish application including live UI updates across browsers in 15 minutes or [livebeats](https://livebeats.fly.dev/larshei).

By now, I have built a hand full web services with Elixir, and where things in other languages become difficult, erlang/elixir really shine (all those servers and services are clustered for example, without and extra tools). 

Some of the open source projects done by the community (and the community itself) are just awesome.

Elixir and Erlang are used by companies like
- Discord
- Ericson
- Financial Times
- Goldmann Sachs
- PepsiCo
- Pinterest
- RabbitMQ -> itself powers a lot of the financial messaging on this planet
- Solaris Bank
- Spotify
- WhatsApp
- ...

[1]: https://www.seppmed.de/elixir-zaubertrank-fuer-digitalisierung/

**Comment by nicolkill** [comment]
Another Framework that its looking great its [Ash Framework](https://www.ash-elixir.org/) that its a plug based framework with ORM and also instant output in Rest or GraphQL

Also used in more companies like `OpticPower (international)`, `Players Lunge (US)`, `VentUp (Mexico)`, `Resuelve (Mexico)`

**Comment by marcusviniciusg03dev** [comment]
I wrote the markdown file to elixir, but i need to draw those dotted lines above.

![Screenshot_20220615-181517_Chrome.jpg](https://user-images.githubusercontent.com/84883298/173931408-232e4bd6-cbcc-41a3-bda8-713f9bbc1674.jpg)

I don't know how to draw it, because it's used html path element that i cannot find in code. I think it's some lib drawing using the json file which contains the roadmap items.

Someone can help me?

**Comment by mingyar** [comment]
@marcusviniciusg03dev, my guess is that you might need to change something here: https://github.com/kamranahmedse/developer-roadmap/blob/838c3759a87c35bd6ce3c0060ba04e52e68af880/content/roadmaps/101-backend/content-paths.json

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmaps by mentioning every available option and are just focusing on what is comparatively more in-demand; comparing Elixir to the listed options, I don't think Elixir is as requested on job boards as the other options..

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
