### ISSUE TITLE
Add Soft-Skills developer roadmap

### ISSUE THREAD

**Issue by arthuralcorrea** [kamranahmedse/developer-roadmap#1122]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue with this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is not to include everything out there in these roadmaps but to have everything that is most relevant today compared to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

What if we put a Developer Soft Skills roadmap into the project.

- The core topics that I'm thinking is something like:
  - Software-domain
  - Customer Orientation 
  - ManagementFundamentals:
    - Estimation and Scheduling
    - Measurement
    - Planing
    - Tracking 

If the community likes the idea we can improve and add more things.

**Comment by YamiTL** [comment]
Pretty cool idea actually, let's hope it gains traction!
