### ISSUE TITLE
Add double click functionality for marking topics in the roadmap as completed instead of having to open the sidebar

### ISSUE THREAD

**Issue by sabinbaniya** [kamranahmedse/developer-roadmap#1129]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

As a user has to click the topic first in any roadmap and then click on mark as completed, it would be better if we could make the double click functionality on topic itself for marking it as completed

**Comment by yanv022** [comment]
Hello,
can I work on this issue ?

Best regards.

**Comment by Subrata287** [comment]
yes why not.

**Comment by yanv022** [comment]
I can't find the Sidebar. Should i suscribe to have access to more Functionality?? Because i tried to suscribe but it's not working.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but we don't have any immediate plans to add the listed functionality to the website. However, it does seem interesting and we will keep it in the backlog 🙏
