### ISSUE TITLE
add another roadmap.

### ISSUE THREAD

**Issue by CurSed0** [kamranahmedse/developer-roadmap#1153]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
hello there
I came here for a request to add a full-stack development roadmap, if possible please add.

**Comment by badolsmito** [comment]
Literally just read both front-end and back-end roadmaps lmao

**Comment by CurSed0** [comment]
Lmfao I didnt realise that sorry
