### ISSUE TITLE
dig command has been mentioned twice in the network section of DevOps roadmap

### ISSUE THREAD

**Issue by tajpouria** [kamranahmedse/developer-roadmap#1158]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

`dig` command has been mentioned twice in the network section.

![image](https://user-images.githubusercontent.com/46822325/155869573-491efddc-64a8-4234-a75d-95aca519cbe7.png)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
