### ISSUE TITLE
error notion with roadmap.sh

### ISSUE THREAD

**Issue by ldanielcolmenaresm** [kamranahmedse/developer-roadmap#1186]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

**Comment by kamranahmedse** [comment]
Hey, I don't understand. Could you please add some description?

**Comment by kamranahmedse** [comment]
Hey, I don't understand. Could you please add some description?

**Comment by ldanielcolmenaresm** [comment]
Basically the problem is that before I could see a preview of the roadmap.sh pages from notion, now I can't see them in notion
