### ISSUE TITLE
Backend roadmap jwt.io link not working as intended

### ISSUE THREAD

**Issue by Neliitsme** [kamranahmedse/developer-roadmap#1211]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Greetings, 
While reading through the guides on a backend developer roadmap I noticed a non-working link to a jwt.io that had one extra slash at the end of the link, so I thought I could open a PR with a fix for this.

**Comment by Neliitsme** [comment]
I already have it fixed in my fork, just need approval to make a request as noted in the contibution docs
