### ISSUE TITLE
Backend dev roadmap broken link

### ISSUE THREAD

**Issue by menteValidus** [kamranahmedse/developer-roadmap#1315]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

In the Backend Developer roadmap in the `What is HTTP?` section `Journey to HTTP/2` link is broken: it's `https://kamranahmed.info/blog/2016/08/13/http-in-depth/` but should be `https://kamranahmed.info/blog/2016/08/13/http-in-depth` to work correctly. Or this link can be handled on a blog website.

**Comment by Goutham-erram** [comment]
Hi can i work on the above issue. if yes, can you assign this to me.

**Comment by kamranahmedse** [comment]
This has been fixed, thank you for reporting.
