### ISSUE TITLE
missed Embedded Software Engineering RoadMap

### ISSUE THREAD

**Issue by LuizFernandoDeveloper** [kamranahmedse/developer-roadmap#1330]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

**Comment by LuizFernandoDeveloper** [comment]
Please add the "Embedded Software Engineering RoadMap"

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
