### ISSUE TITLE
MLOps Roadmap/Enhancement

### ISSUE THREAD

**Issue by kbpersonal** [kamranahmedse/developer-roadmap#1335]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hi, I feel like there would be great benefit to either
-  Enhance the DevOps role to include the learning topics for MLOps with a region in the diagram
OR
- Have a new page entirely for MLOps (there will be a lot of overlap with the DevOps skills)

Personally as a Cloud/Devops engineer I feel like I am a bit lost trying to get into MLOps and understanding where the lines lie between MLOps and an data scientist. Competing public cloud services don't make this easy either with the vendor soup out there.

For reference material, I have not found too much but here are a few references: 
https://medium.com/coriers/mlops-and-machine-learning-roadmap-95efc59927a2
https://github.com/trojrobert/MLOps_roadmap_and_curriculum
https://github.com/cdfoundation/sig-mlops/blob/master/roadmap/2020/MLOpsRoadmap2020.md
https://suhas.org/posts/mlops-2022/

Finally, searching the MLOps subreddit has some good posts:
https://www.reddit.com/r/mlops/search?q=road+to+mlops&restrict_sr=on&include_over_18=on

I am going through how to contribute to the repo and eventually maybe get a PR going but just wanted to get the conversation started for this feature request in terms of generating the actual content for the roadmap. Thank you for all the efforts you have put in to this so far, it is incredible.

**Comment by kamranahmedse** [comment]
Thank you for the roadmap request and for sharing the resources. This would definitely help when we make the roadmap.

We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
