### ISSUE TITLE
Feature Request: Percentage of completion on each roadmap

### ISSUE THREAD

**Issue by linuxdotexe** [kamranahmedse/developer-roadmap#1351]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hey! I really appreciate the work you do. I wanted to ask if you would be open to adding a status of completion percentage. Marking elements as completed works well but I personally think the percentage would be a little more motivational.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but we don't have any immediate plans to add the listed functionality to the website. However, it does seem interesting and we will keep it in the backlog 🙏
