### ISSUE TITLE
 Browser Object Model is missing from the frontend roadmap under Javascript

### ISSUE THREAD

**Issue by sojinsamuel** [kamranahmedse/developer-roadmap#1373]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

The foundation of JavaScript on the web is the Browser Object Model (BOM). The BOM gives us access to objects that reveal the capabilities of the web browser. All front-end developers must know the difference between DOM and BOM. I have some resources in my mind that is super useful for beginners and can use them as references to learn more about DOM.

**Comment by kamranahmedse** [comment]
Thank you for the suggestion, but we are not convoluting the roadmap by mentioning every item available. Anyone who starts learning JavaScript will automatically get to learn that.
