### ISSUE TITLE
Add Developer Relations roadmap

### ISSUE THREAD

**Issue by kuberaspeaking** [kamranahmedse/developer-roadmap#2077]
What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] None of the above

What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](https://github.com/kamranahmedse/developer-roadmap/contributing.md) before opening this issue.

Enter the details about the issue here
- A role in Developer Relations is very sought after especially for generalists. 
- With a lot of tools focusing on developers as the users, more and more companies have started feeling the need for a developer relations team
- Until 5 years ago, Developer Evangelism was meant for someone who usually has an experience of 15+ years. But now you can get involved in this career track early on in your career. 

I can cover the following topics and hoping that others can contribute too.
- Introduction to Developer Relations
  -  What is Developer Relations?
  -  Why do companies need developer relations
  -  What do developer relations teams do?
  - Roles in Developer Relations
    - Developer Advocate
    - Developer Evangelist
    - Developer Marketing
    - Developer Community Manager
- Skills 
  - Content writing
  - Documentation
  - Creating Demos
  - Working with APIs
  - Public Speaking
  - Product Feedback

**Comment by KodeyThomas** [comment]
This would be awesome! 

It's such an underlooked aspect of the industry a roadmap would make a lot of sense for people who've heard about it but have no clue where to start

**Comment by shrirajpawar4** [comment]
Hey @kuberaspeaking, do you mind if I help you with this Dev Rel roadmap?

**Comment by kuberaspeaking** [comment]
if the author @kamranahmedse is okay with it, i'd be happy to work with @shrirajpawar4 on this issue.

**Comment by kuberaspeaking** [comment]
@kamranahmedse can you assign this issue to me for hacktoberfest ?

**Comment by kamranahmedse** [comment]
@kuberaspeaking @shrirajpawar4 go ahead please. Feel free to extend the textual roadmap with how you envision it to be and we will get it converted to the visual format.

**Comment by akshat5302** [comment]
Hello, @kuberaspeaking; I would love to work on this roadmap. Let's do it if you allow me to help and contribute to this fantastic roadmap for devrel, will help a lot of people who are currently looking for a switch or want to get started in this new field 🤟✌

**Comment by kuberaspeaking** [comment]
@akshat5302 would love some help. Maybe you can start with expanding the existing list and then we can divide up the sections. If you have any questions, feel free to ask, we can work together to complete this.

**Comment by akshat5302** [comment]
Everything looks great on the list for a beginner to kick start. One thing to add from my side as of now is that we can add social presence also in the skills section(that is too optional)

**Comment by akshat5302** [comment]
Hey @kuberaspeaking what's next

**Comment by akshat5302** [comment]
Do assign me one of the topics to prepare for that

**Comment by kuberaspeaking** [comment]
Hey @akshat5302 sorry for the delays. You can start with adding resources for the skills under - creating demos and working with APIs, It could be tools or frameworks, YT videos or articles that teach you to make basic demos using something like bootstrap, netlify, heroku or anything else that you might be used to. 
I will be working on introduction

**Comment by akshat5302** [comment]
@kuberaspeaking, can we have a group regarding our conversation cause every time I have to ask my questions here? It would be easy if we have a group on any social media such as Twitter or any other platform

**Comment by akshat5302** [comment]
My question is should I have to make a blog or video regarding APIs, or can I share resources. I'm comfortable with both

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
