### ISSUE TITLE
[Feature Request] - Clicking of ROADMAP items redirect to suggested website for learning.

### ISSUE THREAD

**Issue by sparkeplug** [kamranahmedse/developer-roadmap#650]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I had this idea in the back of my mind, which i think might be useful :

**IDEA :**

What if there is a feature to select the individual items in the ROADMAP TREE, so that it redirects the user to a specific / suggested list of sites to learn those skills OR show a related articles / blogs.

**Comment by mirorauhala** [comment]
Ideally also separates sites that are free or paid. One list for official documentations, blog posts, & tutorial videos. Another for paid courses from reputable vendors.

**Comment by kamranahmedse** [comment]
Not clickable for now but we are working on something for that and will be releasing an update with that by the end of February.
