### ISSUE TITLE
Is there any links with learning staff for each roadmap item?

### ISSUE THREAD

**Issue by dmahmutov** [kamranahmedse/developer-roadmap#665]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

**Comment by dmahmutov** [comment]
It will be a great idea to add some links for each item of your roadmap, for better learning.

**Comment by kamranahmedse** [comment]
Hey, we are progressively adding them. You can have a look at some of the in the [frontend roadmap](https://roadmap.sh/frontend/resources)

**Comment by anticafe** [comment]
Hi @kamranahmedse Could you please add the [frontend roadmap with link](https://roadmap.sh/frontend/resources) to the [ReadMe > Backend Roadmap section](https://github.com/kamranahmedse/developer-roadmap#back-end-roadmap). I think most people (and me too) don't notice there is a such page with useful links.

**Comment by kamranahmedse** [comment]
Thanks @anticafe - I will update that.
