### ISSUE TITLE
Typo on DevOps Roadmap: Startup Management (intid) -> Startup Management (init.d) 

### ISSUE THREAD

**Issue by kashishpatel** [kamranahmedse/developer-roadmap#667]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ X ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ X] Something else

#### Please acknowledge the below listed

- [X ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
Startup Management (intid) -> Startup Management (init.d)

**Comment by praveeno** [comment]
is this just 
> initd -> init.d
I can submit a PR, Please let me know all things to cover.

**Comment by nguyenvulong** [comment]
> is this just
> 
> > initd -> init.d
> 
> I can submit a PR, Please let me know all things to cover.

Only that one, i have double-checked. 
At the moment it is still not fixed.

**Comment by martjanz** [comment]
Still there. No other typo as far as I've seen.

**Comment by inetshell** [comment]
The typo is still there.

**Comment by praveeno** [comment]
hello, should i raise another PR specific for this
https://github.com/kamranahmedse/developer-roadmap/pull/716/commits

**Comment by nguyenvulong** [comment]
> Hello @nguyenvulong @kashishpatel PR for this ticket is raised in #716

which is not fixed (it's almost 2 years already).

**Comment by dev-mirzabicer** [comment]
still not fixed

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
