### ISSUE TITLE
Add Sveltejs to front-end roadmap

### ISSUE THREAD

**Issue by dmidlo** [kamranahmedse/developer-roadmap#710]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I'd like to see Sveltejs added to front-end frameworks. It has a very solid community, it's from the creator of rollup (which has made it on this list), and its development paradigm is that of a compiler and can represent a whole class of front-end frameworks otherwise unrepresented on the roadmap.  

There's a host of other reasons why it should be on the list, but I'll leave it to the wisdom of reviewers and community. :)

**Comment by Upinder123** [comment]
I can help adding it can you tell me where do you want it to be added exactly

**Comment by moigarm** [comment]
Agree with it, Svelte is evolving and even Vue got inspired by it in Vue 3, React with React Hooks

**Comment by seancolsen** [comment]
+1

With the 2020 State of JS survey [having ranked Svelte `#1` in "satisfaction" and `#1` in "interest"](https://2020.stateofjs.com/en-US/technologies/front-end-frameworks/), this roadmap's omission of Svelte seems glaring.

**Comment by moigarm** [comment]
Even Azure has Svelte pre-set on their deployment for sites alongside with Angular, React and Vue

**Comment by JesseKrist** [comment]
Unsubscribe Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Sean Colsen <notifications@github.com> Data: 01/02/21  02:04  (GMT+02:00) A: kamranahmedse/developer-roadmap <developer-roadmap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: Re: [kamranahmedse/developer-roadmap] Add Sveltejs to front-end roadmap (#710) 
+1
With the 2020 State of JS survey having ranked Svelte #1 in "satisfaction" and #1 in "interest", this roadmap's omission of Svelte seems glaring.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
