### ISSUE TITLE
[DevOps Roadmap] Replace Node.js with JavaScript as programming language to learn

### ISSUE THREAD

**Issue by salvatore-piccione** [kamranahmedse/developer-roadmap#720]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [X] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [X] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Node.js is listed among the Programming Languages to learn in DevOps roadmap. According to issue #509 and [Node.js definition](https://nodejs.org/en/about/), Node.js has to be replaced by JavaScript because it is a runtime engine.

**Comment by edisonpebojots** [comment]
Does anyone heard Deno instead of using NodeJS?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
