### ISSUE TITLE
Server Security and Cyber Security Road map

### ISSUE THREAD

**Issue by iamdeepakvishwa** [kamranahmedse/developer-roadmap#750]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

**Comment by astromanish** [comment]
I like to work on this issue.

**Comment by iamdeepakvishwa** [comment]
@astromanish have you planned anything for this

**Comment by luishdez** [comment]
I think this should be integrated ( at least some part of it ) in "devOps" SRE roadmap. Eg. 101 Example Redis/SSH key exploit... or other common pitfalls.
