### ISSUE TITLE
gamifying the roadmap

### ISSUE THREAD

**Issue by ken-sok** [kamranahmedse/developer-roadmap#753]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [Y] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [Y] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [Y] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [Y] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [Y] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I am a junior developer looking at this roadmap, and it does feel a bit overwhelming. So, I suggest there could be a list of suggested projects at each stage to help junior developers measure their progress, and articulate their skills better (sort of like gamifying it). This also helps bring juniors to build more momentum as they would feel that they completed milestones along the way, rather looking at it as a long tough road. Plus, pointing the purpose of concepts can also help make juniors really understand why concepts/techniques could help make their workflow better. 

These are just some suggestions. Hopefully, it can help. 

I appreciate Mr.Ahmed and everyone for helping to build this wonderful project.

**Comment by kamranahmedse** [comment]
Hey, thanks Ken. That's a good idea and we have been actively working on the [next release](https://twitter.com/kamranahmedse/status/1289544806029385728) of these roadmaps which is going to make them interactive and we will have the resources and more details to each of the nodes.

**Comment by ken-sok** [comment]
Hi, Mr. Ahmed. I just found this repo(https://github.com/tuvtran/project-based-learning?fbclid=IwAR1MPYQFxLtm_HYO7UkWhWmtkHUxkunP3l5Bw1QlMN5qIopMgJBmdV7KAzk).  It contains a lot of highly curated links for learning different programming languages and frameworks, and might help you make the roadmaps better.
