### ISSUE TITLE
Question about making roadmap

### ISSUE THREAD

**Issue by Xunzhuo** [kamranahmedse/developer-roadmap#754]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hey bro, I wonder how to make the roadmap picture, by what tools or softwares? I want to make something like these roadmaps

**Comment by kamranahmedse** [comment]
Hey, these are made with [Balsamiq](https://balsamiq.com).
