### ISSUE TITLE
Add new roadmap for mobile developers (Mobile Roadmap)

### ISSUE THREAD

**Issue by erickdaros** [kamranahmedse/developer-roadmap#773]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] Missing Roadmap (Mobile)

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

When i just saw that there was a section for Web Dev Roadmap, that would be nice if we had a roadmap for mobile developers! The roadmap could guide between the basics of mobile what to learn first, native development (iOS or Android) and cross-platform development with some frameworks suggestions as React Native, Flutter or Ionic for example.

**Comment by BROGVOIDOVO** [comment]
8D

**Comment by jh00ny** [comment]
i agree

**Comment by alimertcakar** [comment]
+1 Would be nice.

**Comment by sain06533** [comment]
I too agree, it would be nice

**Comment by josh-Muleshi** [comment]
i was seeking for it, that will be very well

**Comment by Anekenonso** [comment]
I agree, it will be nice to have one

**Comment by mcarval4** [comment]
It would be really nice to have a mobile roadmap for newcomers.

**Comment by gvoliveira** [comment]
I agree with that, it would be nice

**Comment by carlosdeque-s** [comment]
Notify us when it's done, this one can be huge

**Comment by unluomer** [comment]
I agree

**Comment by PuneetGopinath** [comment]
Good, I too have much experience about being a mobile developer
I used termux on android as terminal at that time, see also #384

**Comment by Sridhar-rajendran** [comment]
Surely..

**Comment by harked** [comment]
is this still ongoing?

**Comment by jazz-it** [comment]
Although #584 states it has been fixed, I cound't find "the push".

**Comment by ykws** [comment]
refs #1128 and [Android Developer roadmap](https://roadmap.sh/android)

**Comment by kamranahmedse** [comment]
We now have the [android](https://roadmap.sh/android) and [flutter](https://roadmap.sh/flutter) roadmaps live on the website. iOS and React Native are in progress and will be added soon. Thank you!
