### ISSUE TITLE
Adding a 3D Frontend development branch on Frontend Roadmap

### ISSUE THREAD

**Issue by itsmatin** [kamranahmedse/developer-roadmap#779]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

With computers/browsers processing power improving rapidly, more frontend developers are coding to create 3D websites and components. As this is becoming more common and broader (and even easier to do with libraries such as react-three-fiber), I believe 3D development does deserve a spot on this roadmap.
