### ISSUE TITLE
Writing content of each topic of the roadmap

### ISSUE THREAD

**Issue by NowApoca** [kamranahmedse/developer-roadmap#784]
#### What roadmap is this issue about?

- [] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hi. I have read your roadmaps and they are awesome! I really appreciate that info, it helped me a lot. I would like to contribute writing about each subject of the roadmap. The idea is write about each concept of the cells of the roadmap and share links to books, posts, articles, papers, etc. I know that everyone can search "Algorithm patterns" in google and there will be a lot of info about, but discuss some references will be great.

It just an idea, thanks for writing that roadmaps! Manuel.

**Comment by Blackweather** [comment]
I am all in for the idea, I think it would be a great thing to have a list of resources that help you learn topics mentioned in the cells

**Comment by mojpm** [comment]
I made something similar to this idea but I guess I should've opened an issue

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. Roadmaps are being made interactive and resources are being added for each of the nodes. Frontend and Backend roadmaps are done and can be accessed through [the website](https://roadmap.sh).
