### ISSUE TITLE
Android Developer Roadmap

### ISSUE THREAD

**Issue by prateekcode** [kamranahmedse/developer-roadmap#795]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I would love to see the Android Developer Roadmap for someone who interested in the Mobile App Development. Concepts, Projects, and strategies for building a complete App

**Comment by alvarengaxd** [comment]
hey @prateekcode, they have uploaded a community version of an Android road map in their [website](https://roadmap.sh/). Hope I can help you.

**Comment by prateekcode** [comment]
hey, @alvarengaxd I got it. Thanks

**Comment by asasr** [comment]
fhad1012@icloud.com
