### ISSUE TITLE
Difficulty supporting roadmap.sh via PayPal

### ISSUE THREAD

**Issue by TashaArvanitis** [kamranahmedse/developer-roadmap#810]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hey there! Just wanted to say thanks so much for making and maintaining these roadmaps, they look amazing and I'm looking forward to learning a great deal based on your recommendations.

Just wanted to let you know that your [PayPal link](https://paypal.me/kamranahmedse) (from roadmap.sh) doesn't seem to accept payment.

Here's what I get when I try to send you a few bucks:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/4411956/97886181-e503f200-1ced-11eb-910f-43faec3720dd.png">

Happy to contact paypal support if needed, but wanted to let you know first, in case there's an easy switch you can flip.

**Comment by kamranahmedse** [comment]
Hey Tasha, that's weird I recently received some funds through that link. It could be currency conversion issue, my account was configured to accept only USD, I just changed it to accept any currency, not sure if it was blocking you because of that. But anyway, thanks for the heads up, and for trying to help, appreciate it! :)

**Comment by TashaArvanitis** [comment]
Strange – I am in USD, so doubly weird that it would reject it. Thanks for taking a look, and for all you do.
