### ISSUE TITLE
Do you consider adding the snowpack and vite to module builder of frontend roadmap

### ISSUE THREAD

**Issue by tagnja** [kamranahmedse/developer-roadmap#864]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I want to know your answer about the snowpack and the vite tools. Thanks!

**Comment by Qodestackr** [comment]
@tagnja what is vite? Do I use it with Vuejs only?

**Comment by ishowman** [comment]
> @tagnja what is vite? Do I use it with Vuejs only?

https://vitejs.dev/. It support React and other framework too.

**Comment by kamranahmedse** [comment]
Snowpack is not actively maintained, but Vite was added to the roadmap. Thank you for the suggestion!
