### ISSUE TITLE
Computer Science Roadmap

### ISSUE THREAD

**Issue by peterkibuchi** [kamranahmedse/developer-roadmap#865]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] None of the above

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [X] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

- I think it would be awesome to have a Computer Science Roadmap for people who would like to get/develop a deep understanding of Computer Science.
- More and more people are choosing to go it alone instead of going through college. And some people have [shown that it is indeed possible](https://www.scotthyoung.com/blog/myprojects/mit-challenge-2/). A roadmap would shed light onto what one needs to learn.
- I would also argue that some colleges do a poor job of guiding students through the way, and they would benefit from having a concrete framework/roadmap to guide them.

**Comment by sanchezcarlosjr** [comment]
This is a copy of https://github.com/ossu/computer-science

**Comment by peterkibuchi** [comment]
Goodness. I've checked it out and it's everything one could've asked for and more.

I suppose it's only fair to leave the issue open to enable like minded individuals to find this resource.

Thanks for sharing.

**Comment by kamranahmedse** [comment]
We now have a [computer science roadmap](https://roadmap.sh/computer-science) live at the website.
