### ISSUE TITLE
Add server frameworks for backend roadmap

### ISSUE THREAD

**Issue by gampu** [kamranahmedse/developer-roadmap#869]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [x] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

The backend roadmap has no mention of server(backend) frameworks. Popular frameworks like Ruby on Rails, Django, Express/Node,js and few others should be mentioned under `Frameworks` box for general awareness.

**Comment by TomasMatusek** [comment]
Dont forget to Spring framewrok :)

**Comment by pawelmalak** [comment]
+1 for adding frameworks. Here's a simple mockup of what it could look like:

![frameworks](https://user-images.githubusercontent.com/24780509/140070597-dbedf941-6465-48df-9f72-451b203d3fda.png)

**Comment by gampu** [comment]
Looks nice. But I don't think this repo is maintained regularly. I see a lot of issues and pull requests left ignored. Maybe you can try making a pull request against this issue. All the best!!!.
