### ISSUE TITLE
Kubernetes on Backend roadmap

### ISSUE THREAD

**Issue by alesaudate** [kamranahmedse/developer-roadmap#887]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [X] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

It would be nice to point out Kubernetes on the backend developer roadmap, along with Docker. As we are approaching mid-2021, more and more backend developers are directly in touch with it, not only DevOps people.

**Comment by Ronkiro** [comment]
I think this one needs a bump, Kubernetes popularity is raising fast.

**Comment by kamranahmedse** [comment]
f
This has been fixed and will be published in the coming release. Thank you 🙏
