### ISSUE TITLE
Roadmap just for ruby on rails

### ISSUE THREAD

**Issue by ridhwaans** [kamranahmedse/developer-roadmap#894]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

There is a lot of breadth in rails technologies for different things. a roadmap is useful

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
