### ISSUE TITLE
Blockchain Developer Roadmap

### ISSUE THREAD

**Issue by Omolajacodec** [kamranahmedse/developer-roadmap#925]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue with this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
Blockchain is one of the fast-growing technology. With that in mind, it makes sense that if you want to jump into a career that has a lot of potential for growth, featuring a dynamic new technology that’s just getting started a simplified roadmap is a good place to start.

**Comment by danielgruesso** [comment]
@kamranahmedse this looks good to close.
