### ISSUE TITLE
Adding Fiber to GO roadmap

### ISSUE THREAD

**Issue by mohdule** [kamranahmedse/developer-roadmap#928]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] Go Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [x] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
Hello 👋
Firstly, love these roadmaps a lot 💚👏.
I think the Go lang roadmap is missing one very popular web framework, [Fiber](https://gofiber.io/).
i would love to see it added to the GO lang roadmap.
Thanks 🙏.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
