### ISSUE TITLE
I love this roadmap and want to contribute, but...

### ISSUE THREAD

**Issue by nick-fotopoulos** [kamranahmedse/developer-roadmap#929]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ X ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ X ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ X ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ X ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ X ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Balsamiq cost $90 and limits many people's ability to contribute to the project. This project could really flourish if it used free and open source alternatives like draw.io.

**Comment by kamranahmedse** [comment]
It took ages but we are finally working on a custom editor for making roadmaps. It's almost there and we plan on launching it hopefully by mid September. Thank you!

https://github.com/kamranahmedse/developer-roadmap/assets/4921183/6eeb5807-d386-4823-b5d3-48aec1c59332
