### ISSUE TITLE
Is there gonna be a Vue.js roadmap ?

### ISSUE THREAD

**Issue by ayoub3bidi** [kamranahmedse/developer-roadmap#933]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

So there is a roadmap for React and Angular and I really appreciate that, but what about Vue ?

**Comment by kingma-sbw** [comment]
This was closed because...?

**Comment by ayoub3bidi** [comment]
I felt no one was there to reply so I closed it.

**Comment by ayoub3bidi** [comment]
I checked the [roadmap.sh](https://roadmap.sh) again today and find out they added a lot of new stuff (one of them was the Vue.js roadmap), I guess they are listening 😁after all, so thanks ❤️.
