### ISSUE TITLE
New Request : Blockchain Road Map

### ISSUE THREAD

**Issue by Hironate** [kamranahmedse/developer-roadmap#938]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

As blockchain development accelerating, and there not much wider resources available. Someone should also start making roadmap for Blockchain Development.

**Comment by Mr-Second** [comment]
已收到(自动回复，不要回答！不要回答！不要回答！)

**Comment by danielgruesso** [comment]
@kamranahmedse this looks good to close.
