### ISSUE TITLE
"Migration Strategies" duplicated on Backend Roadmap

### ISSUE THREAD

**Issue by lorenzo-piersante** [kamranahmedse/developer-roadmap#952]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [X] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [X] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

In the Backend roadmap, linked to the "Building for Scale", section there are two duplicate "Migration Strategies" sections.
I recommend removing the duplicate on the right that does not have specified details!

**Comment by kamranahmedse** [comment]
It's "Migration Strategies" and "Mitigation Strategies". Regardless, the section has been updated in the coming release. Thank you!
