### ISSUE TITLE
[Suggestion] Add FastAPI on Python Roadmap as async web framework

### ISSUE THREAD

**Issue by miguelgrubin** [kamranahmedse/developer-roadmap#962]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X] Python Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
[FastAPI](https://fastapi.tiangolo.com/) is one of the most popular asyncrhonous web frameworks nowdays.
Its well documented, fully typed, generates [OpenAPI](https://swagger.io/specification/) specs and it's really easy to learn.

I will share a popularity comparation based on github stars.
|         | Stars | Async |
|---------|-------|-------|
| Django  | 61.2K | ✗     |
| Flask   | 57.4K | ✗     |
| FastAPI | 39.4K | ✓     |
| Tornado | 20.3K | ✓     |
| Sanic   | 15.6K | ✓     |
| aiohttp | 12K   | ✓     |
| Pyramid | 3.6K  | ✗     |

**Comment by tfpgh** [comment]
Second this, just about to open. FastAPI is gaining popularity incredibly quickly and currently far surpasses any other async framework on the roadmap on every [Stack Overflow 2021 Developer Survey metric](https://insights.stackoverflow.com/survey/2021).
