### ISSUE TITLE
FE Roadmap Bug

### ISSUE THREAD

**Issue by vanilla-unicorn** [kamranahmedse/developer-roadmap#966]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Appears that, at least on mobile (iOS), the Frontend Roadmap isn’t loading the interactive version. It does have a link for the non-interactive version but seems the Frontend Roadmap has new nodes but can’t see them on the non-interactive version (as far as I can tell).

**Comment by oliviermap** [comment]
j

**Comment by kamranahmedse** [comment]
@vanilla-unicorn can you please share the browser information and the iOS version? It seems to be working fine for me.

**Comment by vanilla-unicorn** [comment]
Sure thing,

Brave Browse, Version 1.32.3 (21.11.17.19)
iOS Version 14.8 (18H17)

**Comment by kamranahmedse** [comment]
That's strange, it seems to be working fine for me (at least on Brave version 1.33). Could you try again maybe?

![IMG_3849E8312051-1](https://user-images.githubusercontent.com/4921183/148674435-13e7a14b-7c0e-4ac8-825c-2021d1666cf0.jpeg)

**Comment by vanilla-unicorn** [comment]
That's bizarre. I just checked and made sure my auto-update has my Brave at 1.33 now (which it does), but I'm still getting an error only on the frontend roadmap. Other roadmaps show up fine.

**Comment by vanilla-unicorn** [comment]
Confirmed the error shows for both regular and private viewing modes as well.

**Comment by vanilla-unicorn** [comment]
I assume you’re busy on other issues since this isn’t reproducible. You can go ahead and close this issue if that’s the case.

**Comment by kamranahmedse** [comment]
Closing it for now since I am not able to reproduce the issue. However, please comment here or reopen the issue if anyone else is able to reproduce it.
