### ISSUE TITLE
Angular Roadmap: Add Content Projection & ng-container

### ISSUE THREAD

**Issue by ajitzero** [kamranahmedse/developer-roadmap#970]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
  - [x] Angular Roadmap 
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue with this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is not to include everything out there in these roadmaps but to have everything that is most relevant today compared to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

In the [Angular roadmap](https://roadmap.sh/angular):

-  Angular Basics > Rendering Topics: We should separate `<ng-template>` from `ngIf` into its own section, as they are not similar and instead group `<ng-template>` with `<ng-container>` (suggested addition).

- Advanced Topics: `<ng-content>` (suggested addition) is part of the [Content Projection](https://angular.io/guide/content-projection) section which deserves a place in the roadmap.

**Comment by kamranahmedse** [comment]
This has been fixed and is being deployed. Thank you 🙏
