### ISSUE TITLE
[Suggestion] Add SLF4J to Java roadmap

### ISSUE THREAD

**Issue by nkzren** [kamranahmedse/developer-roadmap#972]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] Java Roadmap

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I know SLF4J is not exactly a Logging Framework (the [official website](https://www.slf4j.org/) defines it as a Facade for Logging Frameworks), but since it's so popular AND a useful tool to learn I think it's relevant enough to be in the Java roadmap. Any thoughts? (:

This idea came to me from the recent vulnerability in Log4J. I've seen some companies that used it changing their logging frameworks entirely instead of updating, and SLF4J is quite useful at that.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
