### ISSUE TITLE
Add Typescript roadmap

### ISSUE THREAD

**Issue by jhonywalkeer** [kamranahmedse/developer-roadmap#983]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [X] Add Roadmap

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I'm opening this issue to add the Typescript roadmap (similar to React) where it could contain the following contents: 

### Tets

| Fundamental Topics                             | Ramification                                                                                                                                                          |
| ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Create project with React                      | When to use TSX?                                                                                                                                                      |
| Create project with Node                       | Does not have                                                                                                                                                         |
| Config compiler                                | Config ts.config, ts.config Reference, Compiler Options in MSBuild, tsc CLI Options, Configuring Watch                                                                |
| Types                                          | Everyday Types, Object Types, Complex Types, Union Types, Utility Types, Narrowing, Type Compatibility, Type Inference, Type Compatibility, Type Inference, Interface |
| Typescript Compatible Languages and Frameworks | Does not have                                                                                                                                                         |

| Type Manipulation         | Ramification                                                                         |
| ------------------------- | ------------------------------------------------------------------------------------ |
| Creating Types from Types | Generics                                                                             |
| Keyof Type Operator       | Does not have                                                                        |
| Typeof Type Operator      | Does not have                                                                        |
| Indexed Access Types      | Does not have                                                                        |
| Conditional Types         | Does not have                                                                        |
| Mapped Types              | Does not have                                                                        |
| Template Literal Types    | Does not have                                                                        |
| Classes                   | Does not have                                                                        |
| Modules                   | Module Resolution                                                                    |
| Combinations              | Simple Combinations, Built-in Combinations, User Combinations, Advanced Combinations |

| Advanced Topics          | Ramification                                                                                           |
| ------------------------ | ------------------------------------------------------------------------------------------------------ |
| Decorators               | Does not have                                                                                          |
| Declaration Merging      | Does not have                                                                                          |
| Enums                    | Does not have                                                                                          |
| Iterators and Generators | Does not have                                                                                          |
| Mixins                   | Does not have                                                                                          |
| Namespaces               | Namespaces and Modules                                                                                 |
| .d.ts Templates          | Modules .d.ts, Module: Plugin, Module: Class, Module: Function, Global .d.ts, Global: Modifying Module |
| Consumption              | Packages                                                                                               |

This way it would help the dev's that would go on to integrate languages and libs with Typescript

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
